version: '3.8'
name: u-tech

services:
  redis:
    image: redis:6.2.5
    command: redis-server --requirepass ${REDIS_PASSWORD:-secret}
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - ${REDIS_PORT:-6379}:6379
    networks:
      - utech-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: redis
      REDIS_HOST: redis
      REDIS_PORT: redis:${REDIS_PORT:-6379}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-secret}
      HTTP_USER: ${REDIS_CMD_USER:-root}
      HTTP_PASSWORD: ${REDIS_CMD_PASSWORD:-secret}
    ports:
      - ${REDIS_CMD_PORT:-5051}:8081
    networks:
      - utech-network

networks:
  utech-network:
    driver: bridge

volumes:
  redis:
  redis-config:
  postgres:
  pgadmin: